#!/usr/bin/env tsx
// ============================================================
// Build-time Notion Fetcher
// Run: npm run fetch (or automatically before build via prebuild)
// Writes: src/data/projects.generated.ts
//         src/data/timeline.generated.ts
//
// Output format: canonical LocalizedText {en, he} objects
// matching the Project and TimelineItem interfaces in src/types.
// ============================================================

import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const { fetchProjects, fetchTimeline } = await import('../src/lib/notion');

  const PROJECTS_DB = process.env.NOTION_PROJECTS_DB;
  const TIMELINE_DB = process.env.NOTION_TIMELINE_DB;

  if (!process.env.NOTION_TOKEN) {
    console.error('NOTION_TOKEN is not set. Add it to .env or Vercel env vars.');
    process.exit(1);
  }
  if (!PROJECTS_DB || !TIMELINE_DB) {
    console.error('NOTION_PROJECTS_DB or NOTION_TIMELINE_DB is not set.');
    process.exit(1);
  }

  const outDir = path.resolve(__dirname, '..', 'src', 'data');

  // ---------- Fetch Projects ----------
  console.log('Fetching projects from Notion...');
  const projects = await fetchProjects(PROJECTS_DB);
  console.log(`  ${projects.length} projects fetched`);

  const projectsFile = path.join(outDir, 'projects.generated.ts');
  fs.writeFileSync(
    projectsFile,
    `// Auto-generated by scripts/fetch-notion.ts — DO NOT EDIT\n` +
    `// Last fetched: ${new Date().toISOString()}\n` +
    `import type { Project } from '../types';\n\n` +
    `export const projects: Project[] = ${JSON.stringify(projects, null, 2)};\n`,
    'utf-8'
  );
  console.log(`  Written to ${projectsFile}`);

  // ---------- Fetch Timeline ----------
  console.log('Fetching timeline from Notion...');
  const timeline = await fetchTimeline(TIMELINE_DB);
  console.log(`  ${timeline.length} timeline entries fetched`);

  const timelineFile = path.join(outDir, 'timeline.generated.ts');
  fs.writeFileSync(
    timelineFile,
    `// Auto-generated by scripts/fetch-notion.ts — DO NOT EDIT\n` +
    `// Last fetched: ${new Date().toISOString()}\n` +
    `import type { TimelineItem } from '../types';\n\n` +
    `export const timeline: TimelineItem[] = ${JSON.stringify(timeline, null, 2)};\n`,
    'utf-8'
  );
  console.log(`  Written to ${timelineFile}`);

  console.log('\nNotion data synced successfully!');
}

main().catch((err) => {
  console.error('Fetch failed:', err);
  process.exit(1);
});
