// ============================================================
// Data barrel export — Components import from here
// Uses static imports from generated files
// Run `npm run fetch` to generate them from Notion
// ============================================================

export type { Project, TimelineItem, Lang } from './types';
import type { Project, TimelineItem, Lang } from './types';

// These files are generated by scripts/fetch-notion.ts
// If they don't exist yet, create empty placeholder files or run `npm run fetch`
import { projects as _projects } from './projects.generated';
import { timeline as _timeline } from './timeline.generated';

export const projects: Project[] = _projects;
export const timeline: TimelineItem[] = _timeline;

// --------------- Bilingual Helpers ---------------

export function getProjectField(
  project: Project,
  fieldBase: string,
  lang: Lang
): string {
  const key = `${fieldBase}${lang === 'en' ? 'EN' : 'HE'}` as keyof Project;
  return (project[key] as string) || '';
}

export function getTimelineField(
  item: TimelineItem,
  fieldBase: string,
  lang: Lang
): string {
  const key = `${fieldBase}${lang === 'en' ? 'EN' : 'HE'}` as keyof TimelineItem;
  return (item[key] as string) || '';
}
