// Auto-generated by scripts/fetch-notion.ts — DO NOT EDIT
// Placeholder — run `npm run fetch` to populate from Notion
import type { Project } from './types';

export const projects: Project[] = [];
