// Auto-generated by scripts/fetch-notion.ts — DO NOT EDIT
// Last fetched: 2026-04-26T16:52:47.912Z
import type { Project } from '../types';

export const projects: Project[] = [
  {
    "slug": "ezo-client-campaigns",
    "category": "Digital Marketing",
    "tags": [
      "Meta",
      "Google",
      "Content"
    ],
    "title": {
      "en": "EZO Client Campaigns",
      "he": "קמפיינים של לקוחות EZO"
    },
    "shortDesc": {
      "en": "Multi-client campaigns across retail, services & public sectors.",
      "he": "קמפיינים רב-לקוחיים בקמעונאות, שירותים ומגזר ציבורי."
    },
    "featured": true,
    "client": {
      "en": "Multiple Clients",
      "he": "לקוחות מרובים"
    },
    "detail": {
      "overview": {
        "en": "Managed multi-client digital marketing campaigns across retail, services, and public sectors via Meta, Google Ads, and content strategies.",
        "he": "ניהול קמפיינים דיגיטליים רב-לקוחיים בתחומי קמעונאות, שירותים ומגזר ציבורי."
      },
      "techStack": [
        "Meta Ads",
        "Google Ads",
        "Analytics"
      ]
    }
  },
  {
    "slug": "kheit-cpa",
    "category": "Web Dev",
    "tags": [
      "React",
      "Webflow",
      "CMS"
    ],
    "title": {
      "en": "KHEIT CPA Platform",
      "he": "פלטפורמת KHEIT CPA"
    },
    "shortDesc": {
      "en": "Full-stack CPA management system with admin, employee & client portals.",
      "he": "מערכת ניהול CPA מלאה עם פורטלים למנהל, לעובד וללקוח."
    },
    "url": "https://kheit.com",
    "year": "2024",
    "featured": true,
    "client": {
      "en": "KHEIT CPA",
      "he": "KHEIT רואי חשבון"
    },
    "role": {
      "en": "Full-Stack Developer & Designer",
      "he": "מפתח Full-Stack ומעצב"
    },
    "duration": {
      "en": "3 months",
      "he": "3 חודשים"
    },
    "detail": {
      "overview": {
        "en": "A comprehensive web platform for KHEIT CPA firm, featuring separate portals for administrators, employees, and clients. The system streamlines accounting workflows and client communication.",
        "he": "פלטפורמת אינטרנט מקיפה עבור משרד רואי חשבון KHEIT, הכוללת פורטלים נפרדים למנהלים, עובדים ולקוחות."
      },
      "challenge": {
        "en": "The firm needed a unified digital system to replace fragmented tools and manual processes across three user types.",
        "he": "המשרד נזקק למערכת דיגיטלית אחודה להחלפת כלים מפוזרים ותהליכים ידניים."
      },
      "solution": {
        "en": "Built a role-based platform with dedicated dashboards, document management, and real-time client communication.",
        "he": "נבנתה פלטפורמה מבוססת תפקידים עם לוחות בקרה ייעודיים, ניהול מסמכים ותקשורת בזמן אמת."
      },
      "outcome": {
        "en": "Reduced client onboarding time by 60% and eliminated manual document routing.",
        "he": "זמן קליטת לקוחות צומצם ב-60% והועברו מסמכים באופן אוטומטי."
      },
      "techStack": [
        "React",
        "Webflow",
        "CMS",
        "API Integration"
      ]
    }
  },
  {
    "slug": "meretz-campaigns",
    "category": "PR & Comms",
    "tags": [
      "Politics",
      "Strategy",
      "Media"
    ],
    "title": {
      "en": "Meretz Campaigns",
      "he": "קמפייני מרצ"
    },
    "shortDesc": {
      "en": "PR & Knesset campaign management (2014–2023).",
      "he": "ניהול קמפיינים ויח\"צ לכנסת (2014–2023)."
    },
    "year": "2014–2023",
    "featured": true,
    "detail": {
      "overview": {
        "en": "Managed PR and Knesset campaign strategy for Meretz party from 2014 to 2023, including media management, Arabic community outreach, and multi-platform campaign execution.",
        "he": "ניהול אסטרטגיית קמפיינים ויח\"צ למפלגת מרצ בין 2014 ל-2023. כולל ניהול תקשורת, הסברה בקהילה הערבית וביצוע קמפיינים רב-ערוציים."
      }
    }
  },
  {
    "slug": "orthodont",
    "category": "Branding",
    "tags": [
      "Medical",
      "Logo"
    ],
    "title": {
      "en": "Orthodont Clinic",
      "he": "מרפאת אורתודנט"
    },
    "shortDesc": {
      "en": "Clean, trustworthy brand for a dental clinic.",
      "he": "מותג נקי ואמין למרפאת שיניים."
    },
    "year": "2022",
    "client": {
      "en": "Orthodont Clinic",
      "he": "מרפאת אורתודנט"
    },
    "role": {
      "en": "Brand Designer",
      "he": "מעצב מותגים"
    },
    "duration": {
      "en": "4 weeks",
      "he": "4 שבועות"
    },
    "detail": {
      "overview": {
        "en": "Professional brand identity for an orthodontic clinic — balancing medical credibility with a welcoming patient experience.",
        "he": "זהות מותגית מקצועית למרפאה אורתודנטית — איזון בין אמינות רפואית לחוויית מטופל מזמינה."
      },
      "techStack": [
        "Illustrator",
        "Photoshop"
      ]
    }
  },
  {
    "slug": "raghda-portfolio",
    "category": "Web Dev",
    "tags": [
      "Webflow",
      "Portfolio"
    ],
    "title": {
      "en": "Raghda Portfolio",
      "he": "תיק עבודות רגדה"
    },
    "shortDesc": {
      "en": "Personal portfolio on Webflow.",
      "he": "תיק עבודות אישי ב-Webflow."
    },
    "url": "https://raghda.webflow.io",
    "detail": {
      "overview": {
        "en": "A personal portfolio website built on Webflow, showcasing creative work with a clean, modern design.",
        "he": "אתר תיק עבודות אישי שנבנה ב-Webflow, מציג עבודות יצירתיות בעיצוב נקי ומודרני."
      },
      "techStack": [
        "Webflow"
      ]
    }
  },
  {
    "slug": "revibes",
    "category": "Branding",
    "tags": [
      "Logo",
      "Identity"
    ],
    "title": {
      "en": "Revibes",
      "he": "Revibes"
    },
    "shortDesc": {
      "en": "Modern lifestyle brand with cohesive visual system.",
      "he": "מותג לייפסטייל מודרני עם מערכת ויזואלית אחידה."
    },
    "year": "2023",
    "client": {
      "en": "Revibes",
      "he": "Revibes"
    },
    "role": {
      "en": "Brand Designer",
      "he": "מעצב מותגים"
    },
    "duration": {
      "en": "4 weeks",
      "he": "4 שבועות"
    },
    "detail": {
      "overview": {
        "en": "A fresh lifestyle brand identity built from scratch — logo, color system, and visual guidelines.",
        "he": "זהות מותג לייפסטייל חדשה שנבנתה מאפס — לוגו, מערכת צבעים והנחיות ויזואליות."
      },
      "techStack": [
        "Illustrator",
        "Figma"
      ]
    }
  },
  {
    "slug": "rmf-pgm",
    "category": "Web Dev",
    "tags": [
      "Webflow"
    ],
    "title": {
      "en": "RMF PGM",
      "he": "RMF PGM"
    },
    "shortDesc": {
      "en": "Professional web presence for a medical practice.",
      "he": "נוכחות דיגיטלית מקצועית למרפאה רפואית."
    },
    "url": "https://rmf-pgm.webflow.io",
    "detail": {
      "overview": {
        "en": "A professional web presence for a medical practice, built on Webflow with clean UI and patient-focused design.",
        "he": "נוכחות דיגיטלית מקצועית למרפאה רפואית, נבנתה ב-Webflow עם ממשק נקי ועיצוב ממוקד מטופל."
      },
      "techStack": [
        "Webflow"
      ]
    }
  },
  {
    "slug": "spotless-brand",
    "category": "Branding",
    "tags": [
      "Logo",
      "Social"
    ],
    "title": {
      "en": "Spotless Cleaning Co.",
      "he": "ספוטלס ניקיון"
    },
    "shortDesc": {
      "en": "Fresh, minimal identity for a cleaning company.",
      "he": "זהות רעננה ומינימלית לחברת ניקיון."
    },
    "year": "2023",
    "client": {
      "en": "Spotless Cleaning Co.",
      "he": "ספוטלס ניקיון"
    },
    "role": {
      "en": "Brand Designer",
      "he": "מעצב מותגים"
    },
    "duration": {
      "en": "3 weeks",
      "he": "3 שבועות"
    },
    "detail": {
      "overview": {
        "en": "A clean, fresh brand identity for a professional cleaning service — from logo to social media templates.",
        "he": "זהות מותגית נקייה ורעננה לשירות ניקיון מקצועי — מלוגו ועד תבניות מדיה חברתית."
      },
      "techStack": [
        "Illustrator",
        "Canva"
      ]
    }
  },
  {
    "slug": "spotless-site",
    "category": "Web Dev",
    "tags": [
      "Webflow",
      "Service"
    ],
    "title": {
      "en": "Spotless Site",
      "he": "אתר Spotless"
    },
    "shortDesc": {
      "en": "Full service website for a cleaning company.",
      "he": "אתר שירות מלא לחברת ניקיון."
    },
    "url": "https://sptclean.webflow.io",
    "detail": {
      "overview": {
        "en": "A full-service website for Spotless Cleaning Co., built on Webflow with booking integration and service showcases.",
        "he": "אתר שירות מלא לחברת Spotless Cleaning, נבנה ב-Webflow עם אינטגרציית הזמנות ותצוגת שירותים."
      },
      "techStack": [
        "Webflow"
      ]
    }
  },
  {
    "slug": "swanx",
    "category": "Branding",
    "tags": [
      "Logo",
      "Brand"
    ],
    "title": {
      "en": "SWANX",
      "he": "SWANX"
    },
    "shortDesc": {
      "en": "Bold, minimal brand identity design.",
      "he": "עיצוב זהות מותגית נועז ומינימליסטי."
    },
    "year": "2022",
    "client": {
      "en": "SWANX",
      "he": "SWANX"
    },
    "role": {
      "en": "Brand Designer",
      "he": "מעצב מותגים"
    },
    "duration": {
      "en": "3 weeks",
      "he": "3 שבועות"
    },
    "detail": {
      "overview": {
        "en": "A bold and minimal brand identity for SWANX, emphasizing clean lines and confident visual presence.",
        "he": "זהות מותגית נועזת ומינימליסטית עבור SWANX, עם דגש על קווים נקיים ונוכחות ויזואלית בטוחה."
      },
      "techStack": [
        "Illustrator",
        "Figma"
      ]
    }
  },
  {
    "slug": "tira-meat",
    "category": "Branding",
    "tags": [
      "Logo",
      "Brand Guide",
      "Print"
    ],
    "title": {
      "en": "Tira Meat Boutique",
      "he": "טירה מיט בוטיק"
    },
    "shortDesc": {
      "en": "Premium brand identity — logo, palette, typography & social media kit.",
      "he": "זהות מותגית פרימיום — לוגו, פלטת צבעים, טיפוגרפיה וערכת מדיה חברתית."
    },
    "year": "2023",
    "featured": true,
    "client": {
      "en": "Tira Meat Boutique",
      "he": "טירה מיט בוטיק"
    },
    "role": {
      "en": "Brand Designer",
      "he": "מעצב מותגים"
    },
    "duration": {
      "en": "6 weeks",
      "he": "6 שבועות"
    },
    "detail": {
      "overview": {
        "en": "Complete brand identity system for a premium meat boutique, from logo design through print collateral and social media presence.",
        "he": "מערכת זהות מותגית מלאה לבוטיק בשר פרימיום, מעיצוב לוגו ועד חומרי דפוס ונוכחות ברשתות חברתיות."
      },
      "challenge": {
        "en": "Create a premium yet approachable brand that stands out in a traditional market.",
        "he": "יצירת מותג פרימיום אך נגיש שבולט בשוק מסורתי."
      },
      "solution": {
        "en": "Developed a refined visual identity blending modern design with artisanal butchery aesthetics.",
        "he": "פותחה זהות ויזואלית מעודנת המשלבת עיצוב מודרני עם אסתטיקה של קצביית בוטיק."
      },
      "outcome": {
        "en": "Brand launch drove 40% increase in foot traffic within the first month.",
        "he": "השקת המותג הובילה לעלייה של 40% בתנועת לקוחות בחודש הראשון."
      },
      "techStack": [
        "Illustrator",
        "Photoshop",
        "InDesign"
      ]
    }
  },
  {
    "slug": "tira-municipality",
    "category": "AI & Automation",
    "tags": [
      "Gov-Tech",
      "Automation",
      "Data"
    ],
    "title": {
      "en": "Tira Municipality",
      "he": "עיריית טירה"
    },
    "shortDesc": {
      "en": "Digital transformation across 5 municipal departments.",
      "he": "טרנספורמציה דיגיטלית ב-5 מחלקות עירוניות."
    },
    "year": "2022–2024",
    "featured": true,
    "client": {
      "en": "Tira Municipality",
      "he": "עיריית טירה"
    },
    "detail": {
      "overview": {
        "en": "Led digital transformation across 5 municipal departments including HR, planning, welfare, and vendor portal.",
        "he": "הובלת טרנספורמציה דיגיטלית ב-5 מחלקות עירוניות כולל משאבי אנוש, תכנון, רווחה ופורטל ספקים."
      },
      "techStack": [
        "Power Automate",
        "SharePoint"
      ]
    }
  },
  {
    "slug": "venturexp",
    "category": "Web Dev",
    "tags": [
      "Webflow",
      "Business"
    ],
    "title": {
      "en": "VentureXP",
      "he": "VentureXP"
    },
    "shortDesc": {
      "en": "Business-focused landing page.",
      "he": "דף נחיתה עסקי ממוקד."
    },
    "url": "https://venturexp.ca",
    "year": "2024",
    "client": {
      "en": "VentureXP",
      "he": "VentureXP"
    },
    "role": {
      "en": "Webflow Developer & Designer",
      "he": "מפתח ומעצב Webflow"
    },
    "duration": {
      "en": "2 weeks",
      "he": "שבועיים"
    },
    "detail": {
      "overview": {
        "en": "A conversion-optimized business landing page for VentureXP, a Canadian business services company.",
        "he": "דף נחיתה ממוקד המרה עבור VentureXP, חברת שירותים עסקיים קנדית."
      },
      "techStack": [
        "Webflow",
        "CMS",
        "JavaScript"
      ]
    }
  }
];
